<?php
/********
 * Do not edit this file for making config changes. Change LocalSettings instead
 ********/

// *** Auto load set up
function __autoload($class_name){
	global $IP;
	if (preg_match("/^AdNetwork/", $class_name)){
		require $IP . "AdNetworks/" . $class_name . ".php";
	} else {
		require $IP . $class_name . ".php";
	}
}

// *** Error handling. Note you can change this in your LocalSettings.php
error_reporting(E_ALL ^ E_NOTICE);
ini_set('display_errors', false);
ini_set('log_errors', true);

// These hosts are defined as development hosts, for Framework::isDev()
$DEV_HOSTS = array("localhost");

// Time zone stuff
define('MYSQL_DATE_FORMAT', 'Y-m-d H:i:s');
date_default_timezone_set('America/New_York'); // This suppresses E_STRICT notices when strtotime is called

// Global include settings
$IP = dirname(__FILE__) . '/';

// Default database and memcached settings. Note, do not change here. Override in LocalSettings.php
// See LocalSettings-sample.php as an example
$CONFIG = array(
	'db' => array(),
	'memcached' => array(),
	'homepage_url' => 'http://www.liftium.com'
);

// Pull in the local config for any overrides
if ( file_exists(dirname(__FILE__) . '/LocalSettings.php')){
	include dirname(__FILE__) . '/LocalSettings.php';
} else {
	echo "You need a LocalSettings.php file to set up configs. See LocalSettings-sample.php as an example";
	exit;
}
